spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
#  패키지 아래에있는 Getter setter있는것들을 잡아준다.
  type-aliases-package: com.koreait.facebook

#주소 톰캣포트 바꾸는거 기본 8080
server:
  port: 8090

#FTP File Transfer Protocaol 프로토콜 통신하는 약속
#HTTP Hyper text Transfer Protocol 프로토콜